#!/bin/bash

# Update package list
sudo apt update

# Install Git
sudo apt install -y git

# Clone File Browser repository
git clone https://github.com/filebrowser/filebrowser.git

# Change into the cloned directory
cd filebrowser

# Download the File Browser release
curl -LJO https://github.com/filebrowser/filebrowser/releases/download/v2.26.0/linux-amd64-filebrowser.tar.gz

# Extract the downloaded tar.gz file
tar -xvf linux-amd64-filebrowser.tar.gz

# Build Docker image
docker build -t my-filebrowser .

# Remove the /root/filebrowser folder
rm -rf /root/filebrowser

# Provide optional instructions or further actions
echo "File Browser repository cloned, release downloaded, and Docker image built. You can now run the Docker image using 'docker run my-filebrowser'."

# Exit the script
exit 0
